
name: Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  server-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Stack
        uses: mstksg/setup-stack@v2

      - name: Run a one-line script
        run: | 
          cd Server
          stack test
