
name: Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  server-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Setup Stack
      #   run: curl -sSL https://get.haskellstack.org/ | sh

      - name: Run a one-line script
        run: |
          cd server
          stack test
          
      - name: haskell-stan
        uses: kowainik/stan-action@v0
